#!/bin/bash

# Get the current song by listing all windows and grepping the matching window with the pattern "- Deezer -"
song=$(wmctrl -l -p | grep '\- Deezer -' | sed -n 's/.*'$HOSTNAME'//p');

if [ -z "$song"  ]; then
    echo 'Deezer is currently not palying!';
    exit 1;
else
    # Split the string and only show the name and artist
    delimiter='- Deezer -';
    array=();
    while [[ $song ]]; do
        array+=( "${song%%"$delimiter"*}" );
        song=${s#*"$delimiter"};
    done;
    echo $array;
fi;





