#!/bin/bash
#Grepping out the PID of spotify
spotifyid=$(ps -ef | grep '[/]usr/share/spotify' | awk '{print $2}' | head -1)

#Get the current song by listing all windows and grepping the matching window with the word "Deezer"
currentsong=$(wmctrl -l | grep Deezer | sed -n 's/.*'$HOSTNAME'//p');

if [ -z "$currentsong"  ]; then
    echo 'Deezer is currently not palying!';
    exit 1;
fi;

echo $currentsong;